name: 02-workflow-events.yaml
on: 
    push:
    pull_request:
    workflow_dispatch:
    schedule: 
        - cron: "42 16 * * *"

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: ShowTrigger
              run: |
                echo "Event name: ${{ github.event_name }}"
  